# For more information: https://laravel.com/docs/sail
version: '3'
services:
  webserver:
    container_name: webserver
    image: nginx:latest
    volumes:
      - './nginx/nginx.template.conf:/etc/nginx/nginx.conf'
      # - ./nginx/certbot/conf:/etc/nginx/ssl
      # - ./nginx/certbot/data:/var/www/certbot
    ports:
      - 80:80
      - 443:443
    networks:
      drinkleuca:
        aliases:
          - drinkleuca-webserver
networks:
  drinkleuca:
    driver: bridge
volumes:
  drinkleucaweb:
    driver: local
